create table Users (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
EMAIL VARCHAR, PASSWORD VARCHAR, CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR );

create table StoreAdmins (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
EMAIL VARCHAR, PASSWORD VARCHAR, CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR );

create table malls (ID SERIAL PRIMARY KEY, NAME VARCHAR, DESCRIPTION VARCHAR, 
CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR);

create table stores (ID SERIAL PRIMARY KEY, MALL INT references MALLS(ID), NAME VARCHAR, 
DESCRIPTION VARCHAR, POSITION VARCHAR, ADMIN INT references StoreAdmins(ID), CATEGORY VARCHAR,
CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR);

create table brands (ID SERIAL PRIMARY KEY, NAME VARCHAR, DESCRIPTION VARCHAR,
CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR);

create table products (ID SERIAL PRIMARY KEY, STORE INT references stores(ID), NAME VARCHAR,
BRAND INT references brands(ID), DESCRIPTION VARCHAR,
CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR);

create table orders (ID SERIAL PRIMARY KEY, PRODUCTS INT ARRAY, USERID INT references Users(ID), 
ADDITIONALINFO varchar, CREATEDBY INT, MODIFIEDBY INT, CREATEDAT VARCHAR, MODIFIEDAT VARCHAR);
